### ISSUE TITLE
Smooth vs PerceptualSmooth in legacy vs LabPBR formats

### ISSUE THREAD

**Issue by hardtopnet** [null511/MC-PBR-Pipeline#4]
I noticed you mentioned legacy (AKA OldPBR) being Smooth and LabPBR being perceptual smooth. I suppose the latter means the smoothness is pow2'ed compared to the former.
That's not supposed to be different. Both formats are supposedly using perceptual smoothness. Maybe you might want to create a new option called "OldPBR" that would be the same as legacy but with perceptual smoothness as well ?

**Comment by null511** [comment]
I had a hard time finding much documentation on labPbr (until recently joining Discord); much of what I have is from analyzing existing shaders and [this link](https://github.com/rre36/lab-pbr/wiki/Implementation-Requirements) by rre36. I will update the lab-1.1 format to use perceptual smoothness, thank you for pointing this out!

**Comment by null511** [comment]
`lab-1.1` encoding now using Perceptual Smoothness by default in release 0.4.0 and later. [Wiki](https://github.com/null511/MC-PBR-Pipeline/wiki/PBR-Formats) also updated to better explain defaults and how they can be modified.
